{% set name = "brent-search" %}
{% set version = "1.0.33" %}
{% set sha256 = "7ab4fb74d2c5715a397677af969b475eff4054c6a17b802ffad450317074a86c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - numpy
    - python
    - pytest >=3

test:
  requires:
    - pytest >=3
  imports:
    - brent_search
  commands:
    - python -c "import sys; import brent_search; sys.exit(brent_search.test())"

about:
  home: https://github.com/limix/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "Brent's method for univariate function optimization."
  doc_url: https://brent-search.readthedocs.io
  dev_url: https://github.com/limix/brent-search

extra:
  recipe-maintainers:
    - Horta
