{% set name = "brent-search" %}
{% set version = "2.0.1" %}
{% set sha256 = "6153e7541dc19ded662c7149fdc573d9367c41438d8c0e5dbcc751120b3ecb55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - numpy
    - python
    - pytest >=3

test:
  requires:
    - pytest >=3
  imports:
    - brent_search
  commands:
    - python -c "import sys; import brent_search; sys.exit(brent_search.test())"

about:
  home: https://github.com/limix/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Brent's method for univariate function optimization.
  doc_url: https://brent-search.readthedocs.io
  dev_url: https://github.com/limix/brent-search

extra:
  recipe-maintainers:
    - Horta
