{% set name = "brent-search" %}
{% set version = "1.0.18" %}
{% set sha256 = "f215346451d2e47aa8b2bc47c0e99887c64997277e00ec8171ce38a5daa0b99e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
    - numpy
  imports:
    - brent_search
  commands:
    - python -c "import sys; import brent_search; sys.exit(brent_search.test())"

about:
  home: http://github.com/limix/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Brent's method for univariate function optimization."
  doc_url: http://brent-search.readthedocs.io
  dev_url: https://github.com/limix/brent-search

extra:
  recipe-maintainers:
    - Horta
