{% set name = "brent-search" %}
{% set version = "1.0.28" %}
{% set sha256 = "cfeeddb9be1450b6d3b3f42d37059a187fcdf7a9464e4a9486a86f397217017d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
    - pytest-pep8
    - numpy
  imports:
    - brent_search
  commands:
    - python -c "import sys; import brent_search; sys.exit(brent_search.test())"

about:
  home: https://github.com/limix/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Brent's method for univariate function optimization."
  doc_url: https://brent-search.readthedocs.io
  dev_url: https://github.com/limix/brent-search

extra:
  recipe-maintainers:
    - Horta
