travis:
  secure:
    BINSTAR_TOKEN: PdS+pViNtTY/GEKSq8Nzd/luOoLraVc1qCQTnm9bkusDKWvT9sgf6bB4RxiX1Nrs8vw4HZc0TIMbx5b9ymzN5GxkdbhlgpekXHVR3fQ76OghAgyq4zNVX5IT0E6Wvp7wyAP2zHb8htiA++eAYN8aUe0wdqA964Y0zKF+mveyO6TUF4yKPt2fs5D+5XZjekxtG3nJ1Z+WFJZcOiXUXw7Z7ymt/ttYKgvxezA2kBEhqFBmCYiTLC+illkkmKqd/QQnUlCp32YmVL8rhphTtrhhBwxjagIWZSoWWPe/fhS60TE7jHLDoc9sTNdyTSEHrjjRIEXV4JpJ16dgChaRpITKseI6r6RnyvWFXCnUVai8XvXlGeFEwu7SDdWZvwXxvDp0Q8CbdBYIIp2wFxZ9ZFvHsGAt9dmJ0tGNYbLO3uaCiUvH/e9hFraQ1kwycImKqkUKbLy6vIZbnAqNEq4WKoFJHxD7CRVzoIlAO874YinELo0Q8mU9enlgcduN3Nu1DAq6YbmLL6kxBqtSZ4tdOQcpTcXI0GjYorkOnwBCXMVcDDf1kQQmYV69IweeuovZSxZDX4I1E+JnljogXjcY9oH/0mEbc0z27omaZkPKtKqXPCf1Eej44xdLrtMjyfsRlTClXPEnh1fNbiDyOBCaEUHFKjPL+VBSW52PElwFYWuykpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
