travis:
  secure:
    BINSTAR_TOKEN: NrC/eRvMTreE5TkrEFNtV0JheHWKoIN73JVSOgJj5x+o/CYtu4kl9pjZyMwKHKBXYxoSQtWhZUbhmJfczDPGFven4LCvBaVNfiyrj1fqAd3WEJFz4RjnKWL0YvMNNlkEkZZGW8rZ5HzecP/1UZV2mHO4xLZ1ljXMdvjvLV3NNaGTixXMQfOdzFqbo+Y2JqY1Sq1sxiZ1o5JtMfH9q/ss6f6EaTYOcY68or/1kTWD85mFwnNaGMtAI3tVqAcGt5jhr15zeQD2ZB0BmHGprHFxSkg1v82p/KovX5w6oXhGWpV7DyNvc4g9ErkPL9lWxv9YYQrqQ8N6jATeum1xBWOle1RdL81C4Ltdt+048VMMxYIFdzH8y6iTr4Td/6WBCUGgzXTWYne5lVf7qvqkQvzPHrjWmkhY11O2Xg0sn58klRDgzulCj/H8bokGWQGCgIlRPYg6YLJ1p3cMxhE64hKZ2NA3xHTSX8Q8EVPYMgzYttVXR8ncJ+C2MXD3pCeYCCJEli62W9qEyKxzS2aiSBUuBxRkelkqoIPwopYGkwmkBKT/+VYna0CEnni4+0ZUtMrZJ9D4VagJg4hQtp8vE6A2SGoQpEaaHfJaukXh9KGzT9UIkJHlU6XWyA5zXQZ6bI408XabDYCTk3+HAU1sfl294MGHn/K8KinpmKSX5cNXMrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
