travis:
  secure:
    BINSTAR_TOKEN: m/jn1cs+4A0kY3/ufI+M9HaBk4K3TthZwdqbzdy5IMpg91EwWQ/msXZS0wTa0YBQst+OgcmxzraaSum9BDVkua1Vzw04zKyGLI2pbpighKMUVq5iA2ogaKGMcepFOLGLghEBrqkQ5qStFeFhplUtq70TtncxLsGa8/m+LXxONoNUp0Ix09yW1gfxQnCcbkz+tD63ufHRULX1z/GsUGhS0MysQdJNM5zH6WzCOgoOi3d2rJwOxnNfXde9RKorJ1eKwAhVdB8fVD+MRV0bdMVlWCWtDFL7/hByQTuu0ZMIMcI7ZIT1FXjR43z4lBP1+NBzsp7e+uOnjhAWUJBNsVPQM4fDFnj9K3xM7LqUUj4IvS9+GWs+4KlkJH/MCqkK/yQz+ERT3XjmHZITa4J1kWiGPX44WDjFrBxLLrBjErKuDYo/pBS7czhph85KptrOHyPqaHfZ6yFvsC8O6bPqrnJOmE6+gEIEskDOMto1uyN0F2saGoWRqLNA8hhq2nGVYvjhLQ6a6rbQdxeu0u/+bHewtBG0hE9Dpwl76t5rvVKWIDkcMo/RySG+JE8gQtcYNA9svAjWuvd79ZEJ8uC2hkg48VEBZQPww8RoKwuU8Y7/3mXXJCYuUDUgFuHRtOrkCBzlxM9vCVxv7q60VTTJiVt3rhONSm13tUAMyAcRoun+x98=
appveyor:
  secure:
    BINSTAR_TOKEN: zp6qjghu018/FcRynAuIIzdR9Qg4nEnadfvTvTYB3CdxH2/krZD7s0ZfdeRabVxe
